
from decouple import config


API_KEY = config('API_KEY')
API_SECRET_KEY = config('API_SECRET_KEY')
BASE_URL = config('BASE_URL')
STOCK_API_KEY = config('STOCK_API_KEY')
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER')
CELL_PHONE_NUMBER = config('CELL_PHONE_NUMBER')
ALPHA_ADVANTAGE_KEY = config('ALPHA_ADVANTAGE_KEY')
